cat > deployment.yaml <<EOF
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
    env: homework
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
        env: homework
    spec:
      containers:
      - name: mi-app
        image: fast777/mi-app:baseline
        ports:
        - containerPort: 8080
EOF